<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8696d37b-1a40-4674-a039-35f2d89d5c11</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Software.Api\Software.Api.csproj" />
  </ItemGroup>

</Project>
